### ISSUE TITLE
DKPro Similarity isn't mirrored on Maven Central

### ISSUE THREAD

**Issue by nschimme** [dkpro/dkpro.github.io#1] opened 2015-11-19 00:14 UTC
Hello DK Pro maintainers,

Could we please get DKPro Similarity mirrored on Maven Central? It looks like you've already done this for the other DKPro packages and this one seems to have been missed.

Greatly appreciated,
   Nils

https://dkpro.github.io/dkpro-similarity/

http://search.maven.org/#search%7Cga%7C1%7Cg:"dkpro.similarity" AND a:"dkpro.similarity-asl"

**Comment by nschimme** [comment] 2015-11-19 00:15
This seems to be duplicate of this issue: https://github.com/dkpro/dkpro-similarity/issues/28

**Comment by zesch** [comment] 2015-11-19 08:18
Right, this is a duplicate of #28.
We still don't see a good schedule for a Maven central release, due to the many third parties dependencies.

You can get the dependencies from our artifactory:
<repositories>
<repository>
<id>ukp-oss-releases</id>
<url>http://zoidberg.ukp.informatik.tu-darmstadt.de/artifactory/public-releases</url>
</repository>
<repository>
<id>ukp-oss-snapshots</id>
<url>http://zoidberg.ukp.informatik.tu-darmstadt.de/artifactory/public-snapshots</url>
</repository>
</repositories>

**Closed as completed by zesch** 2015-11-19 08:18 UTC

**Comment by reckart** [comment] 2015-11-19 11:33
It is the wrong project here as well ;) This is the issue tracker for the organization website.

**Comment by areese** [comment] 2015-11-19 16:22
@zesch   you are using artifactory pro you can configure artifactory to publish to bintray.

**Comment by zesch** [comment] 2015-11-19 16:25
Interesting, however we are not using pro.

@areese What would be the benefit of publishing to bintray?

**Comment by reckart** [comment] 2015-11-19 16:28
This is not a technical problem, it is a policy thing. Maven-based tooling by default gets stuff from Maven Central. It is easiest for our users if everything we do is there. Also the dependencies of what we do should be there and they should be published according to best practices, e.g. with source code JAR, properly signed, with a proper pointer to a source repository, with correct license metadata etc.

If we start publishing stuff without source or without proper metadata, then it hinders reproducibility and replicability further down the road.

**Comment by reckart** [comment] 2015-11-19 16:29
We could publish "dirty" stuff to bintray and we could probably even get through publishing dirty stuff to Maven Central - but it is simply not the right thing to do.

**Comment by areese** [comment] 2015-11-19 16:30
bintray is much like maven central. It's run by jfrog who builds artifactory.

**Comment by reckart** [comment] 2015-11-19 16:32
We are actually using Bintray for various projects, particularly resources which don't seem to be suitable for one reason or the other for Maven Central.

**Comment by jbaruch** [comment] 2015-11-19 18:14
Bintray integration is available in both Pro and OSS versions of Artifactory, so you can push to Bintray from OSS and then distribute from there and even sync to Maven Central for the legacy clients.

**Comment by reckart** [comment] 2015-11-19 18:15
@jbaruch how do you define "legacy"? ;)

**Comment by jbaruch** [comment] 2015-11-19 18:20
People who prefer using the package synced to Maven Central and not from Bintray directly.
But it doesn't matter, since the package will be in both places and it won't require any effort (except of initial setup) from your side.

**Comment by reckart** [comment] 2015-11-19 18:40
So let's say the third-party dependencies that we are missing magically appear on Maven Central, but possible without sources or proper poms or such - would we then use them? Probably yes. But we (or at least I!) wouldn't want to be the guy having signed those third-party deploys.

Would we do the same if they magically appeared on Bintray? I can imagine being convinced that having a repo declaration pointing to Bintray's JCenter in our POMs if it has quality dependencies that are not on Maven Central.

Would we deploy our own stuff to Bintray instead of Maven Central? I'd presently not be convinced about this because the default repo in all clients that I know of is Maven Central and that makes it a breeze for users.

Mind the above is my personal opinion or how I would vote if the question came up. Other developers here may have other opinions.

That said - BinTray and Artifactory are really cool - in particular very user friendly!

**Comment by jbaruch** [comment] 2015-11-19 19:05
> So let's say the third-party dependencies that we are missing magically appear on Maven Central, but possible without sources or proper poms or such - would we then use them? Probably yes. But we (or at least I!) wouldn't want to be the guy having signed those third-party deploys.

I don't believe there is some magical way for missing artifacts to appear in Maven Central. Are you referring to 3rd party dependencies, or your own packages?

> Would we do the same if they magically appeared on Bintray? I can imagine being convinced that having a repo declaration pointing to Bintray's JCenter in our POMs if it has quality dependencies that are not on Maven Central.

There are a lot of packages which are in JCenter but not in Maven Central. In this case yes, you need to switch to resolve from JCenter.

> Would we deploy our own stuff to Bintray instead of Maven Central? I'd presently not be convinced about this because the default repo in all clients that I know of is Maven Central and that makes it a breeze for users.

The idea is that it's easier to publish to JCenter and then sync to Maven Central than to publish to Maven Central only. First, Artifactory has 'Push to Bintray' REST API. Second, we take care of the package signing and all the  'release', 'close', 'delete' button clicking in oss.sonatype.org from Bintray, all you need to do is issue a couple of REST API calls (sign and sync to Central).

> Mind the above is my personal opinion or how I would vote if the question came up. Other developers here may have other opinions.

No problem at all. If you don't feel that the benefits I just mentioned are worth it – that's fine, just go with publishing directly to Maven Central. We (JCenter) will know how to make your package available on JCenter as well for the sake of Bintray users.

> That said - BinTray and Artifactory are really cool - in particular very user friendly!

Thanks! That's the idea - making your life easier.

**Comment by reckart** [comment] 2016-01-28 09:48
@nschimme This might be of interest to you: https://github.com/dkpro/dkpro-similarity/issues/28#issuecomment-175142278
